# Generated by Django 4.2.1 on 2023-05-08 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="availability",
            new_name="availabilities",
        ),
    ]
