# Generated by Django 4.2.1 on 2023-05-08 11:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0002_rename_availability_participant_availabilities"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="day",
        ),
        migrations.AddField(
            model_name="availability",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="availability",
            name="end_time",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name="availability",
            name="start_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
