# Generated by Django 4.2.1 on 2023-05-08 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0003_remove_availability_day_availability_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SupportRoleShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.TimeField(default=django.utils.timezone.now)),
                ("end_time", models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="band",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="bandavailability",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="bandavailability",
            name="band",
        ),
        migrations.RemoveField(
            model_name="participantavailability",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="participantavailability",
            name="participant",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="availabilities",
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.DeleteModel(
            name="Band",
        ),
        migrations.DeleteModel(
            name="BandAvailability",
        ),
        migrations.DeleteModel(
            name="ParticipantAvailability",
        ),
        migrations.AddField(
            model_name="participantshift",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="support_signup.participant",
            ),
        ),
        migrations.AddField(
            model_name="participantshift",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="support_signup.role"
            ),
        ),
        migrations.AddField(
            model_name="participantshift",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="support_signup.supportroleshift",
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="shifts",
            field=models.ManyToManyField(
                through="support_signup.ParticipantShift",
                to="support_signup.supportroleshift",
            ),
        ),
    ]
