# Generated by Django 4.2.1 on 2023-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0005_alter_participantshift_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportroleshift",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="supportroleshift",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
