# Generated by Django 4.2.1 on 2023-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0006_alter_supportroleshift_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
