# Generated by Django 4.2.1 on 2023-05-13 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0007_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
