# Generated by Django 4.2.1 on 2023-05-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0008_participant_is_confirmed_participant_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="token",
            field=models.CharField(max_length=100),
        ),
    ]
