# Generated by Django 4.2.1 on 2023-05-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0010_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="role",
        ),
        migrations.CreateModel(
            name="RoleShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support_signup.role",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="support_signup.shift",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="shifts",
            field=models.ManyToManyField(
                through="support_signup.RoleShift", to="support_signup.shift"
            ),
        ),
    ]
