# Generated by Django 4.2.1 on 2023-05-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0011_remove_shift_role_roleshift_role_shifts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="shifts",
            field=models.ManyToManyField(
                through="support_signup.ParticipantShift", to="support_signup.shift"
            ),
        ),
        migrations.AlterField(
            model_name="participantshift",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="support_signup.shift"
            ),
        ),
    ]
