# Generated by Django 4.2.1 on 2023-05-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("support_signup", "0014_delete_schedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participantshift",
            name="role",
        ),
        migrations.AddField(
            model_name="participant",
            name="role",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="support_signup.role",
            ),
            preserve_default=False,
        ),
    ]
